name: Checks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    permissions: write-all
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.25"

      - name: Run tests/lint
        run: |
          set -o pipefail
          git config --global user.email "bob@example.com"
          git config --global user.name "Bob"
          make test lint
        shell: bash

      - name: Annotate
        if: always()
        uses: guyarb/golang-test-annotations@v0.8.0
        with:
          test-results: test-results.json

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.json

      - name: Check coverage
        if: github.ref_name == 'main'
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yaml
          git-token: ${{ secrets.GITHUB_TOKEN }}
          git-branch: badges
